name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install JS deps
        run: npm install

      - name: Install libvips (prebuilt binary)
        shell: pwsh
        run: |
          $vipsver = "8.18.3"
          $dirver = "8.18"
          $url = "https://github.com/libvips/build-win64-mxe/releases/download/v$vipsver/vips-dev-x64-all-$vipsver.zip"
          $zip = "$env:TEMP\vips.zip"
          Write-Host "Downloading $url ..."
          Invoke-WebRequest -Uri $url -OutFile $zip -Verbose
          Write-Host "Extracting $zip to $env:TEMP\vips ..."
          Expand-Archive -Path $zip -DestinationPath "$env:TEMP\vips" -Force -Verbose
          $prefix = "$env:TEMP\vips\vips-dev-$dirver"
          Write-Host "prefix: $prefix"
          echo "VIPS_INCLUDE_DIR=$prefix\include" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "VIPS_LIB_DIR=$prefix\lib" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "$prefix\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "LIB=$prefix\lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build Tauri App
        run: npm run tauri build

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: LuminaConvert-Windows
          path: src-tauri/target/release/LuminaConvert.exe
          if-no-files-found: error
